apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-config
  namespace: default
data:
  certificates.cert-manager.io: |
    {
      "repo": "jetstack",
      "urL": "https://charts.jetstack.io",
      "name": "cert-manager",
      "namespace": "cert-manager",
      "version": "1.0.0"
    }
  servicemonitors.monitoring.coreos.com: |
    {
      "repo": "prometheus-community",
      "urL": "https://prometheus-community.github.io/helm-charts",
      "name": "kube-prometheus-stack",
      "namespace": "monitoring",
      "version": "9.4.4"
    }