
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: traitdefinitions.core.oam.dev
spec:
  group: core.oam.dev
  names:
    categories:
    - crossplane
    - oam
    kind: TraitDefinition
    listKind: TraitDefinitionList
    plural: traitdefinitions
    singular: traitdefinition
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.definitionRef.name
      name: DEFINITION-NAME
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: A TraitDefinition registers a kind of Kubernetes custom resource as a valid OAM trait kind by referencing its CustomResourceDefinition. The CRD is used to validate the schema of the trait when it is embedded in an OAM ApplicationConfiguration.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: A TraitDefinitionSpec defines the desired state of a TraitDefinition.
            properties:
              appliesToWorkloads:
                description: AppliesToWorkloads specifies the list of workload kinds this trait applies to. Workload kinds are specified in kind.group/version format, e.g. server.core.oam.dev/v1alpha2. Traits that omit this field apply to all workload kinds.
                items:
                  type: string
                type: array
              conflictsWith:
                description: 'ConflictsWith specifies the list of traits(CRD name, Definition name, CRD group) which could not apply to the same workloads with this trait. Traits that omit this field can work with any other traits. Example rules: "service" # Trait definition name "services.k8s.io" # API resource/crd name "*.networking.k8s.io" # API group "labelSelector:foo=bar" # label selector labelSelector format: https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Parse'
                items:
                  type: string
                type: array
              definitionRef:
                description: Reference to the CustomResourceDefinition that defines this trait kind.
                properties:
                  name:
                    description: Name of the referenced CustomResourceDefinition.
                    type: string
                  version:
                    description: Version indicate which version should be used if CRD has multiple versions by default it will use the first one if not specified
                    type: string
                required:
                - name
                type: object
              extension:
                description: Extension is used for extension needs by OAM platform builders
                type: object
                x-kubernetes-preserve-unknown-fields: true
              revisionEnabled:
                description: Revision indicates whether a trait is aware of component revision
                type: boolean
              schematic:
                description: Schematic defines the data format and template of the encapsulation of the trait
                properties:
                  cue:
                    description: CUE defines the encapsulation in CUE format
                    properties:
                      template:
                        description: Template defines the abstraction template data of the capability, it will replace the old CUE template in extension field. Template is a required field if CUE is defined in Capability Definition.
                        type: string
                    required:
                    - template
                    type: object
                type: object
              status:
                description: Status defines the custom health policy and status message for trait
                properties:
                  customStatus:
                    description: CustomStatus defines the custom status message that could display to user
                    type: string
                  healthPolicy:
                    description: HealthPolicy defines the health check policy for the abstraction
                    type: string
                type: object
              workloadRefPath:
                description: WorkloadRefPath indicates where/if a trait accepts a workloadRef object
                type: string
            type: object
          status:
            description: CapabilityStatus is the status of WorkloadDefinition and TraitDefinition
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True, False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
