apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-addon-registry
  namespace: vela-system
data:
  registries: '{
  "KubeVela":{
    "name": "KubeVela",
    "oss": {
      "end_point": "https://addons.kubevela.net",
      "bucket": "",
      "path": ""
    }
  },
  "KubeVela-Experimental":{
    "name": "KubeVela-Experimental",
    "oss": {
      "end_point": "https://addons.kubevela.net",
      "bucket": "",
      "path": "experimental/"
    }
  }
}'