apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metricstraits.standard.oam.dev
  namespace: default
  annotations:
    definition.oam.dev/apiVersion: core.oam.dev/v1alpha2
    definition.oam.dev/kind: MetricsTrait
spec:
  appliesToWorkloads:
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
    - deployments.apps
    - statefulsets.apps
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef