apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: routes.standard.oam.dev
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: Route
spec:
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
    - standard.oam.dev/v1alpha1.PodSpecWorkload
    - deployments.apps
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: routes.standard.oam.dev
  extension:
    template: |
      data: {
        apiVersion: "standard.oam.dev/v1alpha1"
        kind:       "Route"
        spec: {
          host: parameter.domain
            path: parameter.path
            tls: {
              issuerName: parameter.issuer
            }
            backend: {
              port: parameter.port
            }
        }
      }
      #route: {
        domain: *"" | string
        path:   *"" | string
        port:   *443 | int
        issuer: *"" | string
      }
      parameter: #route

