{{- if .Values.useWebhook -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: kubevela-mutating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.certificate.certificateName }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutating-core-oam-dev-v1alpha2-applicationconfigurations
    failurePolicy: Fail
    name: mutating.core.oam.dev.v1alpha2.applicationconfigurations
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - applicationconfigurations
        scope: Namespaced
    admissionReviewVersions: 
      - v1beta1
    timeoutSeconds: 5
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutating-core-oam-dev-v1alpha2-components
    failurePolicy: Fail
    name: mutating.core.oam-dev.v1alpha2.components
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - components
        scope: Namespaced
    admissionReviewVersions: 
      - v1beta1
    timeoutSeconds: 5
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-standard-oam-dev-v1alpha1-metricstrait
    failurePolicy: Fail
    name: mmetricstrait.kb.io
    rules:
      - apiGroups:
          - standard.oam.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - metricstraits
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-standard-oam-dev-v1alpha1-podspecworkload
    failurePolicy: Fail
    name: mcontainerized.kb.io
    rules:
      - apiGroups:
          - standard.oam.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - podspecworkloads

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubevela-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.certificate.certificateName }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validating-core-oam-dev-v1alpha2-applicationconfigurations
    failurePolicy: Fail
    name: validating.core.oam.dev.v1alpha2.applicationconfigurations
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - applicationconfigurations
        scope: Namespaced
    admissionReviewVersions: 
      - v1beta1
    timeoutSeconds: 5
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validating-core-oam-dev-v1alpha2-components
    failurePolicy: Fail
    name: validating.core.oam.dev.v1alpha2.components
    rules:
      - apiGroups:
          - core.oam.dev
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - components
        scope: Namespaced
    admissionReviewVersions: 
      - v1beta1
    timeoutSeconds: 5
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-standard-oam-dev-v1alpha1-metricstrait
    failurePolicy: Fail
    name: vmetricstrait.kb.io
    rules:
      - apiGroups:
          - standard.oam.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - metricstraits
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "kubevela.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-standard-oam-dev-v1alpha1-podspecworkload
    failurePolicy: Fail
    name: vcontainerized.kb.io
    rules:
      - apiGroups:
          - standard.oam.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - podspecworkloads

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubevela.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.webhookService.port }}
      protocol: TCP
      name: https
  selector:
    {{ include "kubevela.selectorLabels" . | nindent 6 }}

---
# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certificate.issuerName | quote  }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.certificateName }}
spec:
  dnsNames:
    - {{ template "kubevela.name" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ template "kubevela.name" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.certificate.issuerName  | default "selfsigned-issuer" | quote  }}
  secretName: {{ .Values.certificate.secretName | quote }}
---
{{- end -}}
