apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: metric
  namespace: default
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: MetricsTrait
    definition.oam.dev/description: "Add metric monitoring for workload"
spec:
  appliesToWorkloads:
    - webservice
    - backend
    - task
    - containerizedworkloads.core.oam.dev
    - clonesetworkloads.apps.kruise.io
    - deployments.apps
    - statefulsets.apps
  definitionRef:
    name: metricstraits.standard.oam.dev
  workloadRefPath: spec.workloadRef
  extension:
    template: |-
      output: {
        apiVersion: "standard.oam.dev/v1alpha1"
        kind:       "MetricsTrait"
        spec: {
          scrapeService: parameter
        }
      }
      parameter: {
        // +usage=format of the metrics, default as prometheus
        // +short=f
        format:  *"prometheus" | string
        path:    *"/metrics" | string
        scheme:  *"http" | string
        enabled: *true | bool
        port:    *8080 | >=1024 & <=65535 & int
        // +usage= the label selector for the pods, default is the workload labels
        selector?: [string]: string
      }
      
