apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: route
  annotations:
    definition.oam.dev/apiVersion: standard.oam.dev/v1alpha1
    definition.oam.dev/kind: Route
    definition.oam.dev/description: "Add a route for workload"
spec:
  appliesToWorkloads:
    - webservice
    - deployments.apps
    - podspecworkloads.standard.oam.dev
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: routes.standard.oam.dev
  extension:
    template: |
      output: {
        apiVersion: "standard.oam.dev/v1alpha1"
        kind:       "Route"
        spec: {
          host: parameter.domain
      
          if parameter.issuer != "" {
            tls: {
              issuerName: parameter.issuer
            }
          }
      
          if parameter["rules"] != _|_ {
            rules: parameter.rules
          }
        }
      }
      parameter: {
        domain: *"" | string
        issuer: *"" | string
        rules?: [...{
          path: string
          rewriteTarget: *"" | string
        }]
      }
      
