apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: task
  annotations:
    definition.oam.dev/description: "`Task` is a workload type to describe jobs that run code or a script to completion."
spec:
  definitionRef:
    name: jobs.batch
  extension:
    template: |
      output: {
      	apiVersion: "batch/v1"
      	kind:       "Job"
      	spec: {
      		parallelism: parameter.count
      		completions: parameter.count
      		template: spec: {
      			restartPolicy: parameter.restartPolicy
      			containers: [{
      				name:  context.name
      				image: parameter.image
      
      				if parameter["cmd"] != _|_ {
      					command: parameter.cmd
      				}
      			}]
      		}
      	}
      }
      parameter: {
      	// +usage=specify number of tasks to run in parallel
      	// +short=c
      	count: *1 | int
      
      	// +usage=Which image would you like to use for your service
      	// +short=i
      	image: string
      
      	// +usage=Define job restart policy, the value should be Never or OnFailure. By default, it's Never.
      	restartPolicy: *"Never" | string
      
      	// +usage=Commands to run in the container
      	cmd?: [...string]
      }
      
