apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: config-project1
  namespace: vela-system
  labels:
    config.oam.dev/catalog: "velacore-config"
    config.oam.dev/type: "helm-repository"
spec:
  components:
    - name: deliver-secret
      type: ref-objects
      properties:
        objects:
          - apiVersion: v1
            kind: Secret
            name: image-registry-dev
  policies:
    - type: topology
      name: dev
      properties:
        clusters: ["bj"]
        namespace: default
