{{- if .Values.apiserver.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubevela.name" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevela.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: {{ .Values.apiserver.service.port }}
      protocol: TCP
      name: api
  selector:
    {{- include "kubevela.selectorLabels" . | nindent 6 }}

{{- end -}}