apiVersion: core.oam.dev/v1alpha2
kind: ScopeDefinition
metadata:
  name: healthscopes.core.oam.dev
  namespace: default
spec:
  workloadRefsPath: spec.workloadRefs
  allowComponentOverlap: true
  definitionRef:
    name: healthscope.core.oam.dev