---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  name: workflows.core.oam.dev
spec:
  group: core.oam.dev
  names:
    categories:
    - oam
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    singular: workflow
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Workflow is the Schema for the workflow API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          mode:
            description: WorkflowExecuteMode defines the mode of workflow execution
            properties:
              steps:
                description: Steps is the mode of workflow steps execution
                type: string
              subSteps:
                description: SubSteps is the mode of workflow sub steps execution
                type: string
            type: object
          steps:
            items:
              description: WorkflowStep defines how to execute a workflow step.
              properties:
                dependsOn:
                  description: DependsOn is the dependency of the step
                  items:
                    type: string
                  type: array
                if:
                  description: If is the if condition of the step
                  type: string
                inputs:
                  description: Inputs is the inputs of the step
                  items:
                    properties:
                      from:
                        type: string
                      parameterKey:
                        type: string
                    required:
                    - from
                    - parameterKey
                    type: object
                  type: array
                meta:
                  description: Meta is the meta data of the workflow step.
                  properties:
                    alias:
                      type: string
                  type: object
                name:
                  description: Name is the unique name of the workflow step.
                  type: string
                outputs:
                  description: Outputs is the outputs of the step
                  items:
                    properties:
                      name:
                        type: string
                      valueFrom:
                        type: string
                    required:
                    - name
                    - valueFrom
                    type: object
                  type: array
                properties:
                  description: Properties is the properties of the step
                  type: object
                  
                subSteps:
                  items:
                    description: WorkflowStepBase defines the workflow step base
                    properties:
                      dependsOn:
                        description: DependsOn is the dependency of the step
                        items:
                          type: string
                        type: array
                      if:
                        description: If is the if condition of the step
                        type: string
                      inputs:
                        description: Inputs is the inputs of the step
                        items:
                          properties:
                            from:
                              type: string
                            parameterKey:
                              type: string
                          required:
                          - from
                          - parameterKey
                          type: object
                        type: array
                      meta:
                        description: Meta is the meta data of the workflow step.
                        properties:
                          alias:
                            type: string
                        type: object
                      name:
                        description: Name is the unique name of the workflow step.
                        type: string
                      outputs:
                        description: Outputs is the outputs of the step
                        items:
                          properties:
                            name:
                              type: string
                            valueFrom:
                              type: string
                          required:
                          - name
                          - valueFrom
                          type: object
                        type: array
                      properties:
                        description: Properties is the properties of the step
                        type: object
                        
                      timeout:
                        description: Timeout is the timeout of the step
                        type: string
                      type:
                        description: Type is the type of the workflow step.
                        type: string
                    required:
                    - name
                    - type
                    type: object
                  type: array
                timeout:
                  description: Timeout is the timeout of the step
                  type: string
                type:
                  description: Type is the type of the workflow step.
                  type: string
              required:
              - name
              - type
              type: object
            type: array
        type: object
    served: true
    storage: true
