apiVersion: v1
data:
  application: |
    apiVersion: core.oam.dev/v1beta1
    kind: Application
    metadata:
      annotations:
        addons.oam.dev/description: Prometheus is an open-source systems monitoring and
          alerting toolkit
      name: prometheus
      namespace: vela-system
    spec:
      components:
      - name: prometheus
        properties:
          chart: premetheus
          repoType: helm
          url: https://prometheus-community.github.io/helm-charts
        type: helm
      workflow:
        steps:
        - name: checking-depends-on
          properties:
            name: fluxcd
            namespace: vela-system
          type: depends-on-app
        - name: apply-resources
          type: apply-application
    status: {}
kind: ConfigMap
metadata:
  annotations:
{{- with .Values.addons.prometheus.configMapAnnotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
    addons.oam.dev/description: Prometheus is an open-source systems monitoring and
      alerting toolkit
    addons.oam.dev/name: prometheus
  labels:
    addons.oam.dev/type: prometheus
  name: prometheus
  namespace: {{.Values.systemDefinitionNamespace}}
