apiVersion: v1
appVersion: 0.13.0
description: Crossplane is an open source Kubernetes add-on that extends any cluster
  with the ability to provision and manage cloud infrastructure, services, and applications
  using kubectl, GitOps, or any tool that works with the Kubernetes API.
home: https://crossplane.io
icon: https://crossplane.io/images/favicon_192x192.png
keywords:
- cloud
- infrastructure
- services
- application
- database
- cache
- bucket
- infra
- app
- ops
- oam
- gcp
- azure
- aws
- alibaba
- cloudsql
- rds
- s3
- azuredatabase
- asparadb
- gke
- aks
- eks
maintainers:
- email: info@crossplane.io
  name: Crossplane Maintainers
name: crossplane
version: 0.13.0
