name: SDK Test

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    paths:
      - "vela-templates/definitions/**"
      - "pkg/definition/gen_sdk/**"
    branches:
      - master
      - release-*

permissions:
  contents: read

env:
  # Common versions
  GO_VERSION: '1.19'
  GOLANGCI_VERSION: 'v1.49'

jobs:
  sdk-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Go tools
        run: |
          make goimports
          make golangci

      - name: Build CLI
        run: make vela-cli

      - name: Build SDK
        run: bin/vela def gen-api -f vela-templates/definitions/internal/ -o ./kubevela-go-sdk --package=github.com/kubevela-contrib/kubevela-go-sdk --init

      - name: Validate SDK
        run: |
          cd kubevela-go-sdk
          go mod tidy
          golangci-lint run --timeout 5m -e "exported:" -e "dot-imports" ./...
