name: sync-api
on:
  push:
    paths:
      - 'apis/**'
      - 'pkg/oam/**'
    tags:
      - "v*"

permissions:
  contents: read

env:
  GO_VERSION: '1.19'

jobs:
  sync-core-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Sync to kubevela-core-api Repo
        env:
          SSH_DEPLOY_KEY: ${{ secrets.VELA_API_DEPLOY }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/apis/clientgen.sh
          bash ./hack/apis/sync.sh sync
